# Generated by Django 4.1.7 on 2023-04-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object',
        ),
    ]
