# Generated by Django 4.1.6 on 2023-03-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_testmodel_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='NewsFeed',
        ),
    ]
