# Generated by Django 4.1.6 on 2023-03-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_test_newsfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(default='lastname', max_length=100)),
                ('first_name', models.CharField(default='firstname', max_length=100)),
                ('address', models.CharField(default='address', max_length=100)),
                ('phone_number', models.CharField(default='phone', max_length=100)),
                ('email', models.CharField(default='email', max_length=100)),
                ('date_of_birth', models.CharField(default='dob', max_length=100)),
            ],
        ),
    ]
