# Generated by Django 4.1.7 on 2023-03-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_user_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
