# Generated by Django 4.1.7 on 2023-03-27 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='lastname', max_length=100)),
                ('first_name', models.CharField(default='firstname', max_length=100)),
                ('address', models.CharField(default='address', max_length=100)),
                ('phone_number', models.CharField(default='phone', max_length=100)),
                ('date_of_birth', models.DateField(default='dob', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
