# Generated by Django 4.1.7 on 2023-04-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_reservation_number_of_guests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
