# Generated by Django 4.1.7 on 2023-04-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('8:00', '8:00'), ('9:30', '9:30'), ('11:00', '11:00'), ('12:30', '12:30'), ('2:00', '2:00'), ('3:30', '3:30'), ('5:00', '5:00')], max_length=100),
        ),
    ]
