name: TCRS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # build source for unit tests
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: tennis-club-reservation-system
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
  # build shared objects
  migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make Migrations
        working-directory: tennis-club-reservation-system/tcrs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py makemigrations

      - name: Migrate
        working-directory: tennis-club-reservation-system/tcrs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py migrate